name = "BiNormalDistribution"
uuid = "35cb82aa-8885-40e5-a2ce-8461cb5c8dfc"
authors = ["Abhro R. and contributors"]
version = "0.0.3-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Distributions = "0.25"
ForwardDiff = "0.10, 1"
KernelDensity = "0.6.9"
Peaks = "0.5.3"
QuadGK = "2.11.2"
Random = "1"
Roots = "2"
Statistics = "1"
julia = "1.10"
